import {readFile, writeFile} from 'node:fs/promises';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const bundlePath = resolve(root, 'inapp-renderer/vendor/manim-web.browser.js');
const runtimePath = resolve(root, 'inapp-renderer/runtime.js');
const outputPath = resolve(root, 'src/visualization/inAppRendererHtml.ts');

const [bundle, runtime] = await Promise.all([
  readFile(bundlePath, 'utf8'),
  readFile(runtimePath, 'utf8'),
]);

const safeScript = value => value.replaceAll('</script', '<\\/script');
const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' data:; img-src data: blob:; style-src 'unsafe-inline'; connect-src 'none'; media-src data: blob:;" />
    <style>
      html, body, #scene { width: 100%; height: 100%; margin: 0; overflow: hidden; background: #1c1c1c; }
      canvas { display: block; width: 100%; height: 100%; }
    </style>
  </head>
  <body>
    <main id="scene" aria-label="Mathematical visualization"></main>
    <script>${safeScript(runtime)}</script>
    <script>window.__POCKETPAL_BOOTSTRAP__(${JSON.stringify(bundle)});</script>
  </body>
</html>`;

const source = `// Generated by inapp-renderer/scripts/build_inapp_renderer.mjs. Do not edit manually.\nexport const IN_APP_RENDERER_ENGINE_VERSION = '0.3.24';\nexport const IN_APP_RENDERER_HTML = ${JSON.stringify(html)};\n`;
await writeFile(outputPath, source);
console.log(`Wrote ${outputPath} (${source.length} bytes)`);
